### ISSUE TITLE
BoxType filter in Api does not work

### ISSUE THREAD

**Issue by albertog78** [ZencashOfficial/Sidechains-SDK#47]
Instead of specifying the boxType class name as filter, specify the serialization code identifier (both custom and core bytes)

**Comment by g666** [comment]
The filter works as expected.
Below two examples of request and response:
```
REQUEST
{ "boxTypeClass": "com.horizen.box.PublicKey25519NoncedBox" }
RESPONSE
{
  "result": {
    "boxes": []
  }
}

REQUEST
{ "boxTypeClass": "com.horizen.box.RegularBox" }
RESPONSE
{
  "result": {
    "boxes": [
      {
        "typeId": 1,
        "proposition": {
          "publicKey": "bf126e8d1db806f1b7d6ec11449c7c9218228c80675c8a46ebcef53b57c4ee40"
        },
        "value": 3000000000,
        "id": "688d7ba57f96f24ab6bd24736cf3186dbb1ba54dc1c37c592e0b6c7e53d80054",
        "nonce": -4913201148643714000
      },
      {
        "typeId": 1,
        "proposition": {
          "publicKey": "1d71af035aacbc874e10529cb5bf85e51f1d6583882d32d2a05683dfd7763016"
        },
        "value": 5000000000,
        "id": "d279ba11d001677d604db67fd0c97c536294df50f7e514c000d6b4a33f476086",
        "nonce": 5871814066128264000
      }
    ]
  }
}
```
If we want to specify the serialization code identifier, the user, to create a box with unique identifier, must to know all identifiers, of the boxes, already defined inside the system. And for do this, we should to provide to the user all predefined identifiers.

Specifying the class name, the only constraint is that it's not possible to retrieve all boxes of a certain type where the type is either an interface or an abstract class. We can think if we want or not also this feature in the future (we have this constraint even if we specify the serialization code identifier). But at moment, next step is only to extend unit tests to cover the expected behaviour of the system

**Comment by g666** [comment]
Solved in commit (https://github.com/ZencashOfficial/Sidechains-SDK/commit/ad22a2f9b1ec1bf7caee5def6200f392368a51fc)
